# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado2/project_10.1/project_10.1.cache/wt [current_project]
set_property parent.project_path D:/Vivado2/project_10.1/project_10.1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado2/project_10.1/project_10.1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/zxt12138/Desktop/计算机系统/Lab10-code/coe/lab10_all.coe
read_verilog C:/Users/zxt12138/Desktop/计算机系统/Lab10-code/src/AluOp.vh
read_verilog -library xil_defaultlib -sv {
  C:/Users/zxt12138/Desktop/计算机系统/Lab10-code/src/IO_Manager.sv
  C:/Users/zxt12138/Desktop/计算机系统/Lab10-code/src/Top.sv
}
read_verilog -library xil_defaultlib {
  D:/Vivado2/project_10.1/project_10.1.srcs/sources_1/new/ALU.v
  C:/Users/zxt12138/Desktop/计算机系统/Lab10-code/src/Control_sim.v
  C:/Users/zxt12138/Desktop/计算机系统/Lab10-code/src/Core.v
  D:/Vivado2/project_10.1/project_10.1.srcs/sources_1/new/Datapath.v
  D:/Vivado2/project_10.1/project_10.1.srcs/sources_1/new/ImmGen.v
  D:/Vivado2/project_10.1/project_10.1.srcs/sources_1/new/MUX2T1_32.v
  D:/Vivado2/project_10.1/project_10.1.srcs/sources_1/new/PC.v
  D:/Vivado2/project_10.1/project_10.1.srcs/sources_1/new/Regs.v
  C:/Users/zxt12138/Desktop/计算机系统/Lab10-code/src/SCPU.v
}
read_ip -quiet D:/Vivado2/project_10.1/project_10.1.srcs/sources_1/ip/Ram/Ram.xci
set_property used_in_implementation false [get_files -all d:/Vivado2/project_10.1/project_10.1.srcs/sources_1/ip/Ram/Ram_ooc.xdc]

read_ip -quiet D:/Vivado2/project_10.1/project_10.1.srcs/sources_1/ip/Rom_1/Rom.xci
set_property used_in_implementation false [get_files -all d:/Vivado2/project_10.1/project_10.1.srcs/sources_1/ip/Rom_1/Rom_ooc.xdc]

read_edif C:/Users/zxt12138/Desktop/计算机系统/Lab10-code/src/Control.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/zxt12138/Desktop/计算机系统/Lab10-code/constrs/nexys_a7.xdc
set_property used_in_implementation false [get_files C:/Users/zxt12138/Desktop/计算机系统/Lab10-code/constrs/nexys_a7.xdc]


synth_design -top Top -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
