# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado2/project_10.1/project_10.1.srcs/sources_1/ip/Ram/Ram.xci
# IP: The module: 'Ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado2/project_10.1/project_10.1.srcs/sources_1/ip/Ram/Ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Vivado2/project_10.1/project_10.1.srcs/sources_1/ip/Ram/Ram.xci
# IP: The module: 'Ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado2/project_10.1/project_10.1.srcs/sources_1/ip/Ram/Ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
