webtalk_init -webtalk_dir D:/Vivado2/project_10.1/project_10.1.sim/sim_1/behav/xsim/xsim.dir/Core_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul  2 21:40:28 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "13f7a25e-25a6-40e1-b26f-a753f6d8373a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "50892f55e5f94d48b0850c66d2ca48ef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "90" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "39924020 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.90_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16124_KB" -context "xsim\\usage"
webtalk_transmit -clientid 276253589 -regid "" -xml D:/Vivado2/project_10.1/project_10.1.sim/sim_1/behav/xsim/xsim.dir/Core_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Vivado2/project_10.1/project_10.1.sim/sim_1/behav/xsim/xsim.dir/Core_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Vivado2/project_10.1/project_10.1.sim/sim_1/behav/xsim/xsim.dir/Core_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
